### ISSUE TITLE
Publish to pypi?

### ISSUE THREAD

**Issue by chenrui333** [CycodeLabs/raven#117]
👋 I might be better to also publish the release tarball to pypi as well.

**Comment by elad-pticha** [comment]
@alex-ilgayev @oreenlivnicode

**Comment by alex-ilgayev** [comment]
I think we can do it.
We need to mention that the package on its own won't work without redis and neo4j,
but once they are up, it can be easily run following `pip3 install ...`

**Comment by chenrui333** [comment]
Hi folks, thanks for publishing the artifact in pypi, but somehow I could not find it in the registry, can you point me to it? Thanks!

**Comment by elad-pticha** [comment]
Hey, we are going to publish `raven` as `raven-cycode` because `raven` is already taken. We still have not published it but only prepared everything before the publishing. We need to replace `py2neo` with the new one inside the repository (https://github.com/CycodeLabs/raven/pull/153).

**Comment by elad-pticha** [comment]
We also recalled version `v1.0.5` until PR: https://github.com/CycodeLabs/raven/pull/153 will be resolved.

**Comment by chenrui333** [comment]
yeah, I saw the release was recalled, it would be better to roll forward :) (just my two cents)

**Comment by elad-pticha** [comment]
@chenrui333 we release v1.0.5, and also now `raven` is in [pypi](https://pypi.org/project/raven-cycode/)

**Comment by chenrui333** [comment]
awesome thanks!!
