### ISSUE TITLE
What permissions are needed for Slack notifications of the report?

### ISSUE THREAD

**Issue by shnmorimoto** [CycodeLabs/raven#123]
When I tried the Slack notification function of Report, the following error was output. 

```
[x] Failed to send report: missing_scope
```

The command I tried is below.

```
raven report --severity critical --tag injection slack --slack-token <slack token> --channel-id <channel-id>
```

I had granted the Slack token the permissions for `chat:write` and `chat:write:public`. 

What permissions are required for Slack notifications?

**Comment by elad-pticha** [comment]
The required permissions are: `files:read` and `files:write.`
The latest RAVEN version uses file upload API for the report (differently from the older RAVEN version that sent the report as plain text)


We definitely should add this to the documentation.

**Comment by elad-pticha** [comment]
Make sure to remove the Raven app from the channel -> reinstall the app in the workspace and add the Raven app again. Please ping us if the issue continues

**Comment by shnmorimoto** [comment]
Thank you. 

After granting those permissions and trying, I was able to successfully send the report to Slack.

**Comment by elad-pticha** [comment]
I am keeping this issue open for adding docs about the required permissions.
