### ISSUE TITLE
fix: limit github actions workflow permissions

### ISSUE THREAD

**Issue by alex-ilgayev** [CycodeLabs/raven#142]
**Describe the bug**
At the moment the CI workflows running with high permissions for the `GITHUB_TOKEN`.
More info here: https://docs.github.com/en/actions/security-guides/automatic-token-authentication

**Expected behavior**
Limiting permissions in the workflow using the `permissions` tag.

**Comment by elad-pticha** [comment]
@alex-ilgayev Pipelines are running with: Contents, Metadata and packages `read` permissions. Are you referring to the PR test pipelines or something else?
