### ISSUE TITLE
The data is not going into the neo4j console

### ISSUE THREAD

**Issue by mdburwood** [CycodeLabs/raven#143]
Seeing if anyone else is getting this issue after running `raven index`

**Comment by elad-pticha** [comment]
Thank you for opening this issue! Can you please add some pictures and add more descriptions to this issue?

**Comment by mdburwood** [comment]
Yep so after `raven index` we have a successful execution of code as shown below. Afterwards, heading towards neo4j, there is no databases or index of any sort of data as shown below. 
<img width="1436" alt="Screenshot 2023-11-09 at 4 38 36 PM" src="https://github.com/CycodeLabs/raven/assets/149010118/35852d2c-cc36-433a-9a8a-742432b94db3">
<img width="341" alt="Screenshot 2023-11-09 at 4 39 39 PM" src="https://github.com/CycodeLabs/raven/assets/149010118/fc525c84-7b36-4a93-ae74-ffb4a574977c">

**Comment by oreenlivnicode** [comment]
Don't you have an option to choose neo4j DB?
![image](https://github.com/CycodeLabs/raven/assets/131685203/c35c0873-78d3-45ae-a84e-c8dad8cce1be)

**Comment by mdburwood** [comment]
I already tired that and there was no databases.

**Comment by elad-pticha** [comment]
OK, Thank you @mdburwood 🙏
I have a couple of questions:
1) Can you share if you used `org`/`crawl` mode for the download process? Is it possible that no workflows were found during the download process?
2) Can you please check if the Redis DB has any data? If it is empty, it means that the download process did not find any workflows.

**Comment by mdburwood** [comment]
- Ah so I used org, but for the RavenDemo org it does work. 
- I did check the Redis DB and there isn't any data. 
- I did try this with no data, I have tried this with raven download org --token $GITHUB_TOKEN --org-name RavenDemo the data will show but other queries doesn't. At this current moment I get the following error. 

status code: 403. Response: {
  "message": "Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization.",
  "documentation_url": "https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/"
}

**Comment by elad-pticha** [comment]
It might be due to some limitations on `RavenDemo`. Please try to scan any other public GitHub organization (that contains repositories with workflows). Please let us know if that solves the issue.

**Comment by mdburwood** [comment]
So the RavenDemo goes through and it is populated in the database but now I'm trying to index my own company and I get the following error about indexing the workflow. 


<img width="1436" alt="Screenshot 2023-11-09 at 4 38 36 PM" src="https://github.com/CycodeLabs/raven/assets/149010118/2e522ccf-6549-44cc-b5f0-ef7e763df3eb">

**Comment by elad-pticha** [comment]
It seems like a specific problem with the workflow file. It may be an invalid workflow file.
Can you share the file (if possible)? if not, please make sure the workflow itself is valid.

**Comment by mdburwood** [comment]
I'm just using the org as burwood and getting errors with that.

**Comment by elad-pticha** [comment]
It may be a specific issue to this workflow (if it continues for the rest of the workflows, please ping me on this).
Have the rest of the workflows been indexed?

**Comment by mdburwood** [comment]
It has been indexed.
