### ISSUE TITLE
make setup 

### ISSUE THREAD

**Issue by xXxSpicyBoiiixXx** [CycodeLabs/raven#162]
There appears to be some issue with `make setup` in the docker container. Would we need the to pre-allocate some containers before doing so or should this be automatic? Some context, I am on a Ubuntu machine.

**Comment by elad-pticha** [comment]
Hey!
Thank you for opening this issue.
Can you please send screenshots/error trace so we can inspect the problem?
`make setup` should work fine if you have `docker-compose` v2.

**Comment by xXxSpicyBoiiixXx** [comment]
Ah that's what the issue was I had docker-compose v1, which solved the issue after installing docker-compose-v2. In addition to note for Linux users, you will have to run `sudo make setup`
