### ISSUE TITLE
Expand GitHub Token documentation regarding required scopes.

### ISSUE THREAD

**Issue by thanasisk** [CycodeLabs/raven#170]
**Is your feature request related to a problem? Please describe.**
When creating GitHub tokens (classic ones), you get presented with quite a few options. This can be problematic for new users and might compromise the principle of least privilege per token.

**Describe the solution you'd like**
List only the required GitHub token scopes and nothing more, nothing less.

**Comment by elad-pticha** [comment]
Hey, thank you for taking the time to open this issue. We have updated the wiki. Check it out at: https://github.com/CycodeLabs/raven/wiki/Tokens-&-Permissions
